CREATE TYPE STATUS AS ENUM ('active','inactive');

create table sessions (
    ID SERIAL PRIMARY KEY,
    TOKEN TEXT NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS STATUS NOT NULL DEFAULT 'active',
    UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ID INT REFERENCES USERS(ID)
);

CREATE TABLE ASSETS (
    ASSET_ID SERIAL PRIMARY KEY,
    ASSET_NAME VARCHAR(120) NOT NULL,
    URL TEXT,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_INGESTED BOOLEAN DEFAULT FALSE,
    UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS STATUS NOT NULL DEFAULT 'active'
)